eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: AccAPI
  datasource:
    name: GES
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter: stat
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://192.168.66.200:1433;DatabaseName=GES
      username: sa
      password: yywhiter_nb1818
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 20000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
mybatis:
  type-aliases-package: ges.Entity
  mapper-locations: classpath:mapper/*.xml